Indexer core
oceanprotocol/ocean-node pull request #103
Opened 2023-11-09 07:18 UTC by bogdanfazakas

Fixes #21 .

Changes proposed in this PR:

- [x] create config and take list of : RPC,chainId,chunkSize from env for every network,
  need to add **chunkSize**
- [x] for each network, start a working thread (use nodejs Working Threads)
- [x] should detect the block used to deploy the contracts from addresses.json
- [x] should store the last indexed block. if none, use above
   need db interaction to save the last indexed block and get the last indexed block
- [x] check network height, if > than last indexed block, process remaining blocks in chunks. If something fails, reduce chunk size to 1/2 and retry
- [x] based on event, use a specific processor
- [x] if something fails or processing of an event takes more that than a couple of secs, insert that event to a retry queue and move to next one

2023-11-20 06:14 UTC, alexcos20 requested changes

2023-11-20 06:14 UTC, alexcos20 commented on src/components/Indexer/crawlerThread.ts
> +  if (networkHeight > startBlock) {
what happends once we processed all blocks?
Thread should be sleeping, and from time to time get the new height and process more blocks.

From your code(let me know if I'm wrong) looks like it's going to process once and then stop.

2023-11-20 06:37 UTC, alexcos20 commented on src/components/Indexer/utils.ts
> +export const processBlocks = async (
also, process block by block is going to be a pain
we need to filter a chunk of blocks by events, using provider.getLogs

2023-11-20 07:03 UTC, bogdanfazakas commented on src/components/Indexer/crawlerThread.ts
> +  if (networkHeight > startBlock) {
good catch, thanks forgot to update the heigth in a timeout, will push that

2023-11-20 07:05 UTC, bogdanfazakas commented on src/components/Indexer/utils.ts
> +    fs.readFileSync(
got it so we should add an address.json file and fallback to that , i think aqua is doing something similar atm

2023-11-20 09:15 UTC, paulo-ocean requested changes
Hi @bogdanfazakas 
Just a couple of suggestions as i think you could make a little bit better use of our custom logger :-)
for instance, when you create the custom Logger you could specify the module as 'Indexer, rather than 'Database'
```
export const INDEXER_LOGGER: CustomNodeLogger = getCustomLoggerForModule(
  LOGGER_MODULE_NAMES.DATABASE, // INDEXER
  LOG_LEVELS_STR.LEVEL_INFO,
  defaultConsoleTransport
)
```
And when you're logging, you could set the log level directly by calling '`log(level,message,includeModuleName)`' // include module name
instead of always setting log level before and after the message, like:

```
INDEXER_LOGGER.loggerOptions.level = LOG_LEVELS_STR.LEVEl_ERROR
INDEXER_LOGGER.logMessage('Error retrieving last indexed block')
INDEXER_LOGGER.loggerOptions.level = LOG_LEVELS_STR.LEVEL_INFO
```

thanks :+1:

2023-11-20 09:21 UTC, bogdanfazakas commented
> Hi @bogdanfazakas Just a couple of suggestions as i think you could make a little bit better use of our custom logger :-) for instance, when you create the custom Logger you could specify the module as 'Indexer, rather than 'Database'
> 
> ```
> export const INDEXER_LOGGER: CustomNodeLogger = getCustomLoggerForModule(
>   LOGGER_MODULE_NAMES.DATABASE, // INDEXER
>   LOG_LEVELS_STR.LEVEL_INFO,
>   defaultConsoleTransport
> )
> ```
> 
> And when you're logging, you could set the log level directly by calling '`log(level,message,includeModuleName)`' // include module name instead of always setting log level before and after the message, like:
> 
> ```
> INDEXER_LOGGER.loggerOptions.level = LOG_LEVELS_STR.LEVEl_ERROR
> INDEXER_LOGGER.logMessage('Error retrieving last indexed block')
> INDEXER_LOGGER.loggerOptions.level = LOG_LEVELS_STR.LEVEL_INFO
> ```
> 
> thanks 👍

thanks for the hints, will update

2023-11-21 05:17 UTC, alexcos20 commented on src/components/Indexer/utils.ts
> +    const blockLogs = await provider.getLogs({
We need to add all topics that we are looking for, otherwise we will get all logs, from all contracts on the network :)

2023-11-21 05:20 UTC, alexcos20 commented on src/utils/address.ts
> +export const addressFile = {
why don't you "npm i @oceanprotocol/contracts" ? :)

2023-11-21 08:06 UTC, bogdanfazakas commented on src/utils/address.ts
> +export const addressFile = {
aa ok i think missundertood the initial comment 🤦 , like not to use ocean-contracts 😄 
will update :)

2023-11-21 08:38 UTC, bogdanfazakas commented on src/components/Indexer/utils.ts
> +    const blockLogs = await provider.getLogs({
got it, finally, so we should filter a chunk of blocks with topics that are hashes of the events we want to catch 😃

2023-11-21 08:47 UTC, alexcos20 commented on src/utils/address.ts
> +export const addressFile = {
we will need contracts anyway for events, provider functionality, etc.. so let's have it now

2023-11-21 13:51 UTC, alexcos20 approved these changes

2023-11-21 15:55 UTC, paulo-ocean approved these changes
alright :+1:

2023-11-21 15:57 UTC, merged