Added env vars for IPFS and ARWEAVE gateways.
oceanprotocol/ocean-node pull request #114
Opened 2023-11-15 12:41 UTC by mariacarmina

Fixes # .

Changes proposed in this PR:

- added env vars for IPFS and ARWEAVE gateways in README.md and Dockerfile

@alexcos20 mentioned [that](https://github.com/oceanprotocol/ocean-node/pull/94#discussion_r1393960952) once we have a native IPFS connection, we won't need the gateway, but for the moment I specified it.

2023-11-15 13:33 UTC, jamiehewitt15 commented on README.md
> +For storing the file on IPFS or ARWEAVE, please export the following env variables;
What files are we storing on IPFS and Arweave?

2023-11-15 13:37 UTC, mariacarmina commented on README.md
> +For storing the file on IPFS or ARWEAVE, please export the following env variables;
If you have IPFS file or Arweave file object assigned to the DDO, you need to specify the gateways. It is a follow-up issues for https://github.com/oceanprotocol/ocean-node/pull/94.

2023-11-15 13:41 UTC, jamiehewitt15 commented on README.md
> +For storing the file on IPFS or ARWEAVE, please export the following env variables;
Ah ok, yeah makes sense

2023-11-15 13:42 UTC, jamiehewitt15 commented on README.md
> +For storing the file on IPFS or ARWEAVE, please export the following env variables;
But it's for downloading the files, rather than storing them?

2023-11-15 14:22 UTC, mariacarmina commented on README.md
> +For storing the file on IPFS or ARWEAVE, please export the following env variables;
yes, I was referring to store in the DDO, I'll change into downloading. Thanks!

2023-11-15 14:38 UTC, jamiehewitt15 approved these changes
Looks good to me

2023-11-15 14:52 UTC, alexcos20 requested changes
let's do it properly:
 - add them to Config object
 - do checks at startup

2023-11-15 14:56 UTC, mariacarmina commented
> let's do it properly:
> 
> * add them to Config object
> * do checks at startup

Ok, sure, thank you.

2023-11-15 15:42 UTC, paulo-ocean approved these changes
LGTM

2023-11-16 08:07 UTC, alexcos20 approved these changes

2023-11-16 08:09 UTC, merged