PR for APIs backward compatible
oceanprotocol/ocean-node pull request #137
Opened 2023-12-01 17:25 UTC by an7e

Fixes #133 

Changes proposed in this PR:

- added service router
- added api methods

2023-12-11 16:40 UTC, paulo-ocean commented on src/components/httpRoutes/index.ts
> +httpRoutes.use('/api/service/', providerRoutes)
isn't the path `/api/service**s**/` ? :-)

2023-12-11 17:17 UTC, paulo-ocean commented on src/components/httpRoutes/provider.ts
> +providerRoutes.post('/encrypt', async (req, res) => {
Shouldn't we use the handler functions we already have?  for instance, turning the incoming request into the equivalent "directCommand" task ?
Most of these, we implemented as directCommands, so maybe it makes some sense to try to reuse some of that handler logic?

We are also not logging anything, neither the errors (just sending 500 error back) , and not validating the inputs (which we already have on the directCommands)
I think its important to look at this in more detail, since we are going to rely on the CLI for testing, and pretty much we will just use these legacy endpoints

This does not apply to all endpoints, but for encrypting, getting fees, nonce, findDDO, etc, we already have some handler functions that might be handy as they have more checks already implemented, 
my 2 cents
tkx

2023-12-12 10:30 UTC, alexcos20 commented on src/components/httpRoutes/aquarius.ts
> +    const { did } = req.params
check if did is passed, otherwise send proper http error code

2023-12-12 10:30 UTC, alexcos20 commented on src/components/httpRoutes/aquarius.ts
> +    const { did } = req.params
check if did is passed

2023-12-12 10:33 UTC, alexcos20 commented on src/components/httpRoutes/provider.ts
> +providerRoutes.post('/encrypt', async (req, res) => {
I agree as well.  http routes shoud have no command logic, only some params checking for proper error msg

2023-12-12 10:34 UTC, alexcos20 commented on src/index.ts
> +  app.use(express.raw())
out of curiosity, why do we need this?

2023-12-12 13:29 UTC, an7e commented on src/components/httpRoutes/index.ts
> +httpRoutes.use('/api/service/', providerRoutes)
lol missed that

2023-12-12 13:42 UTC, an7e commented on src/components/httpRoutes/aquarius.ts
> +    const { did } = req.params
but i passed
```
if (result.stream) {
      const ddo = JSON.parse(await streamToString(result.stream as Readable))
      res.json(ddo)
    } else {
      res.status(result.status.httpStatus).send(result.status.error) <= HERE
    }
```
or did I misunderstand?

2023-12-12 13:50 UTC, an7e commented on src/index.ts
> +  app.use(express.raw())
to be able to get data in req.body
```
providerRoutes.post('/encrypt', async (req, res) => {
  try {
    const data = Uint8Array.from(req.body)
    const encryptedData = await encrypt(data, 'ECIES')
    if (encryptedData) {
      res.send(encryptedData)
    } else {
      res.status(400).send()
    }
  } catch (error) {
    res.status(500).send('Internal Server Error')
  }
})
```
without it 
`const data = Uint8Array.from(req.body)`
will be empty

2023-12-12 13:58 UTC, paulo-ocean commented on src/components/httpRoutes/provider.ts
> +providerRoutes.post('/encrypt', async (req, res) => {
Not sure if i'm following you here:
Your encrypHandler does:
```
// do encrypt magic
 const encryptedData = await encrypt(blobData, task.encryptionType)
```
```
which is the same thing you're doing on the provider route:
const encryptedData = await encrypt(data, 'ECIES')
```
What's the difference here? It looks the same to me.
you could still use handleEncryptCommand(
{... }
)

2023-12-13 10:49 UTC, paulo-ocean requested changes

2023-12-13 10:49 UTC, paulo-ocean commented on src/components/httpRoutes/aquarius.ts
> +aquariusRoutes.get('/aquarius/state/ddo', async (req, res) => {
This route is not correct:
should be only `/state/ddo` not` /aquarius/state/ddo` because you already have: `/api/aquarius`  on all these routes before... like this it becomes `/api/aquarius/aquarius/state/ddo`

2023-12-13 10:58 UTC, paulo-ocean requested changes

2023-12-13 10:58 UTC, paulo-ocean commented on src/components/httpRoutes/aquarius.ts
> +    res.status(500).send('Internal Server Error')
you should have logs on the errors at least, these are calls are throwing error, and having only the 500 error does not help (when testing, i had to put a console.log to be able to understand the issue)
The problem is on `handleGetDdoCommand` and `handleQueryCommand`
when you're constructing the response stream with 
`Readable.from(string)` 
better use instead:
`new ReadableString(string)`
The function `streamToString(stream)` is complaining about the args

2023-12-13 11:09 UTC, paulo-ocean requested changes

2023-12-13 11:09 UTC, paulo-ocean commented on src/components/httpRoutes/aquarius.ts
> +      const queryResult = JSON.parse(await streamToString(result.stream as Readable))
there's another issue here:
the returned `queryResult` object is an array, like `[{"facet_counts":[],"found":1,"hits":[{"document":{"`
so, the  check `queryResult.found` fails because it should be `queryResult[0].found` (same for the other references bellow)
and inside the `hits[0]` there is the `nft.state` is inside `document`
instead of `queryResult.hits[0].nft.state` should be something like:
`queryResult[0].hits[0].document.nft.state`
thanks

2023-12-13 11:11 UTC, paulo-ocean commented
btw, i used postman for testing all the routes.. once we fix these issues i think we're good...
It would be nice to have param checking and more logging, but i guess we can do that after POC

2023-12-13 18:01 UTC, paulo-ocean approved these changes
lgtm :+1:

2023-12-13 20:29 UTC, alexcos20 approved these changes
lgtm. if bugs are found, will fix them later
@an7e - can you open a PR later just for download ?

2023-12-13 20:30 UTC, merged