Index order events
oceanprotocol/ocean-node pull request #145
Opened 2023-12-06 12:19 UTC by mariacarmina

Fixes #125  .

Changes proposed in this PR:

- index OrderStarted
- index OrderReused
- tests

2023-12-06 15:15 UTC, mariacarmina commented
needs integration tests

2023-12-11 09:42 UTC, mariacarmina commented
CURRENT PROBLEM:

`getERC721Address` smart contract function retruns a different NFT address -> returns a different DID checksum which cannot be identified in the DB.
For metadata events, `event.address` (which is == NFT address) is a different address (rather than `getERC721Address`) and stores the DDO with a certain checksum which does not correspond with the one generated in OrderStarted processor.

2023-12-11 13:23 UTC, mariacarmina commented
Here is the source code from the contracts which sets the `erc721Address` https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L268.

2023-12-11 22:00 UTC, bogdanfazakas commented
Maria is it enough to just update the stats.orders ? this is basically just replacing what we have in current aquarius, but from my understanding we should also have a new schema and store order informations that are stored in the subgraph at for the moment ?

2023-12-11 22:03 UTC, bogdanfazakas commented on src/components/Indexer/eventProcessor.ts
> +export const processOrderReusedEvent = async (
processOrderReusedEvent is so pretty much using same code as processOrderStartedEvent so think we can refactor a bit and get rid of as many code duplications as possible

2023-12-11 22:04 UTC, mariacarmina commented
> Maria is it enough to just update the stats.orders ? this is basically just replacing what we have in current aquarius, but from my understanding we should also have a new schema and store order informations that are stored in the subgraph at for the moment ?

From the last week discussion, I understood from @alexcos20 that the pricing (which was previously retrieved from subgraph into aquarius) will be tackled in the frontend component (which will interact directly with the smart contracts). @alexcos20 suggested that I should keep in DDO only orders counter.

2023-12-12 05:17 UTC, bogdanfazakas commented
> > Maria is it enough to just update the stats.orders ? this is basically just replacing what we have in current aquarius, but from my understanding we should also have a new schema and store order informations that are stored in the subgraph at for the moment ?
> 
> From the last week discussion, I understood from @alexcos20 that the pricing (which was previously retrieved from subgraph into aquarius) will be tackled in the frontend component (which will interact directly with the smart contracts). @alexcos20 suggested that I should keep in DDO only orders counter.

I remember this talk and wasn't it about the price from the stats? And we decided to not add it there, but that should have nothing to do with storing the actual order info and reused order info like we have in the subgraph. But let's see other opinions as well and we'll move fwd.

2023-12-12 06:01 UTC, alexcos20 requested changes
We need to store orders in the database, and I'm not seeing that in the code.
Primary use case is to check if an existing order is still valid.
Orders != Price schema  (which indeed, price schemas can be fetched realtime from contracts)

2023-12-13 20:17 UTC, bogdanfazakas commented on tests/integration/indexer.test.ts
> +    console.log('nftAddress for OrderStarted test: ', nftAddress)
remove this

2023-12-13 20:17 UTC, bogdanfazakas commented on tests/data/orderSchema.ts
> +    { name: 'type', type: 'string', enum: ['startOrder', 'reuseOrder'] },
In the current subgraph we have reuses of an orders as a property within that order, is it ok to have them indexed have as separate entities with the current implementation ? will this break things thinking of backwards compatibility ?

2023-12-13 20:17 UTC, bogdanfazakas commented on src/components/Indexer/eventProcessor.ts
> +      await dbconn.order.create(
not really sure of how we are dealing with this kind of events that require the update 2 models in the database, in this case we are using the newly created instance from the save the order , and passing back the ddo to the main thread to store it using the original db connection.

2023-12-13 20:17 UTC, bogdanfazakas commented on src/components/Indexer/eventProcessor.ts
> +    INDEXER_LOGGER.logMessage(`Found did ${did} on network ${chainId}.`)
lets delete this

2023-12-13 20:17 UTC, bogdanfazakas commented on src/components/Indexer/eventProcessor.ts
> +  INDEXER_LOGGER.logMessage(`Decoded event data args: ${decodedEventData.args}`, true)
we can delete this i guess since we have a better log bellow

2023-12-13 20:58 UTC, mariacarmina commented on tests/data/orderSchema.ts
> +    { name: 'type', type: 'string', enum: ['startOrder', 'reuseOrder'] },
That was @alexcos20  proposal. I followed it accordingly.

2023-12-13 21:30 UTC, mariacarmina commented
> without the more detailed things like the order schema or how we work with the db

From what I've discussed with @alexcos20, the preferred schema was something that follows this model:
```json 
{
 id:   txID,
 type: 'startOrder' | 'reuseOrder'
 timestamp: block.timestamp,
 consumer,
 payer,
 startOrderId: (doar daca e de type reuse)
}
```
@alexcos20 can you confirm as well and review it?

2023-12-19 14:49 UTC, alexcos20 approved these changes

2023-12-19 14:49 UTC, bogdanfazakas approved these changes

2023-12-19 15:42 UTC, merged