add default fee tokens if not configured
oceanprotocol/ocean-node pull request #151
Opened 2023-12-07 16:39 UTC by paulo-ocean

Fixes #142 

Changes proposed in this PR:

- always have default values for FEE_TOKENS and FEE_AMOUNT, even if not configured
- refactor some related code
- common util function for getting artifacts addresses
- some related cleaning on the env. vars + logging

2023-12-08 10:10 UTC, alexcos20 requested changes

2023-12-08 10:10 UTC, alexcos20 commented on src/utils/address.ts
> +export const OCEAN_TOKEN_ADDRESS_PER_CHAIN = {
no need for hardcoding, you can find them in address.json, see https://github.com/oceanprotocol/contracts/blob/main/addresses/address.json

2023-12-08 10:15 UTC, paulo-ocean commented on src/utils/address.ts
> +export const OCEAN_TOKEN_ADDRESS_PER_CHAIN = {
yeah, i missed that, we are already importing it in other place
thanks

2023-12-12 05:52 UTC, alexcos20 commented on src/components/core/feesHandler.ts
>    return result.length ? result[0].token : null
you should return zero address (0x0000000000000000000000000000000000000000) instead of null

2023-12-12 08:20 UTC, paulo-ocean commented on src/components/core/feesHandler.ts
>    return result.length ? result[0].token : null
alright, thanks. just updated it

2023-12-12 10:06 UTC, bogdanfazakas approved these changes

2023-12-12 10:36 UTC, alexcos20 approved these changes
lgtm

2023-12-12 11:54 UTC, merged