PR Support ddo credentials in download 170
oceanprotocol/ocean-node pull request #183
Opened 2023-12-19 20:36 UTC by an7e

Fixes #170

Changes proposed in this PR:

- added check credentials to allow/deny access
- additional validation of ddo

2023-12-20 06:40 UTC, alexcos20 requested changes
this is not complete

2023-12-20 06:40 UTC, alexcos20 commented on src/components/core/downloadHandler.ts
> +  if (ddo.credentials) {
please create a function, like all other checks

2023-12-20 06:40 UTC, alexcos20 commented on src/components/core/downloadHandler.ts
> +          credential.values.includes(consumerCredentials.values[0])
how do you handle case mismatches ?

2023-12-20 06:40 UTC, alexcos20 commented on src/components/core/downloadHandler.ts
> +
where are the tests?

2023-12-20 06:41 UTC, alexcos20 commented
and tests are failing

2023-12-20 12:17 UTC, an7e commented on src/components/core/downloadHandler.ts
> +
@alexcos20 There are two tests here, one implicit - the bootstrap test has the consumer address specified in DDO as allowed, and another one explicit - test should not allow to download the asset with different consumer address

2023-12-20 13:41 UTC, alexcos20 requested changes

2023-12-20 13:41 UTC, alexcos20 commented on src/utils/credentials.ts
> +  // check deny access
deny should always come first in checks

2023-12-20 13:41 UTC, alexcos20 commented on tests/integration/download.test.ts
> +  it('should not allow to download the asset with different consumer address', async function () {
can you create unit tests for checkCredentials with different scenarios?

2023-12-21 11:27 UTC, alexcos20 approved these changes

2023-12-21 13:29 UTC, bogdanfazakas approved these changes
lgtm

2023-12-21 13:29 UTC, merged