Feature/ Refactor indexer
oceanprotocol/ocean-node pull request #202
Opened 2024-01-04 14:21 UTC by bogdanfazakas

Fixes #199  .

Changes proposed in this PR:

- 
- 
-

2024-01-08 12:48 UTC, an7e commented on src/components/Indexer/processor.ts
> +    const dbconn = await new Database(await (await this.getConfiguration()).dbConfig)
Let's make a dbconn parameter in the constructor that requires a ready-made database instance so that we can write this kind of code
import Database
```
const DB = await new Database(await (await this.getConfiguration()).dbConfig)

somewhere
const eventProcess = BaseEventProcessor(DB)

class BaseEventProcessor {
  protected config: OceanNodeConfig
  protected dbconn: Database
  constructor(dbconn) {
    this.config = null // config would even be redundant in a case like this
    this.dbconn = dbconn
  }
```

2024-01-16 10:00 UTC, mariacarmina reviewed
Couple of comments for better understanding, thanks!
Can we also update the description of the PR to see what we include in the refactor?

2024-01-16 10:00 UTC, mariacarmina commented on src/components/Indexer/processor.ts
> +      this.createOrUpdateDDO(ddo, EVENTS.ORDER_REUSED)
For me it's unclear why we pass `EVENTS.ORDER_REUSED` as method for createOrUpdateDDO. Should it be changed or do you have another reason behind for this?

2024-01-16 10:00 UTC, mariacarmina commented on src/components/Indexer/processor.ts
> +      if (method === EVENTS.METADATA_CREATED) {
If we include update metadata event in `createOrUpdateDDO`, we need to also check for `EVENTS.METADATA_UPDATED`, `EVENTS.METADATA_STATE` and order events for logging the right event. Is it correct?

2024-01-16 11:31 UTC, paulo-ocean commented on src/components/Indexer/processor.ts
> +      if (method === EVENTS.METADATA_CREATED) {
i think the main reason why we are passing the event is mainly, because on a case of adding a new DDO to DB, we need to advertise to the network that we are serving as providers of that ID (emit an event).
And that can be only done after a successful DB operation.   So, its either passing the event to that function, or do it outside, but for that the `createOrUpdateDDO` would have to return something, like a boolean for instance.
In any case, i cannot see any place anymore where we are passing `METADATA_CREATED` to that function, so it seems to me that this part bellow is already broken:
```
if (method === EVENTS.METADATA_CREATED) {
        INDEXER_DDO_EVENT_EMITTER.emit(EVENTS.METADATA_CREATED, saveDDO.id)
      }
```

2024-01-17 09:24 UTC, paulo-ocean commented on src/components/Indexer/processor.ts
> +      if (method === EVENTS.METADATA_CREATED) {
@bogdanfazakas is this ever called? I don´t think we are passing this event anymore, so no event will ever be emmited

2024-01-17 09:50 UTC, bogdanfazakas commented on src/components/Indexer/processor.ts
> +      if (method === EVENTS.METADATA_CREATED) {
good catch thx, there is a mistake here https://github.com/oceanprotocol/ocean-node/pull/202/files#diff-18c89330be3d05a89e8fa07b7e16560745d6ad5af06e8e7e4e81007f7b1f6961R122 will update it to be ` EVENTS.METADATA_CREATED` instead of `EVENTS.ORDER_REUSED` but should be called

2024-01-17 09:52 UTC, bogdanfazakas commented on src/components/Indexer/processor.ts
> +      if (method === EVENTS.METADATA_CREATED) {
yep of this check is to advertise new DDO's by using the emit method, and that is the reason we have the check here after the ddo is saved and we advertise only new ddo's not updated ones

2024-01-17 09:55 UTC, bogdanfazakas commented on src/components/Indexer/processor.ts
> +      this.createOrUpdateDDO(ddo, EVENTS.ORDER_REUSED)
good point, the method param can also be optional, 
but think it would be good to know also when updating the the ddo the event that triggered it within the logs, so will update this to reflect it `INDEXER_LOGGER.logMessage(
        `Saved or updated DDO  : ${saveDDO.id} from network: ${this.networkId} triggered by ${method} event !`
      )`

2024-01-17 15:50 UTC, paulo-ocean commented
btw @bogdanfazakas i see that the event is being emited now, but its not "listened" anymore on the P2P node... so something else must have changed on the refactor

2024-01-17 15:55 UTC, bogdanfazakas commented
> btw @bogdanfazakas i see that the event is being emited now, but its not "listened" anymore on the P2P node... so something else must have changed on the refactor

hmm should be there just updated the import path in the P2P index file
https://github.com/oceanprotocol/ocean-node/pull/202/files#diff-f1ac505a4ab708dae670df1269cd81836276455e82e45e296447566142268a7aL126

2024-01-17 16:00 UTC, paulo-ocean requested changes

2024-01-17 16:00 UTC, paulo-ocean commented on src/components/Indexer/index.ts
> -export const INDEXER_DDO_EVENT_EMITTER = new EventEmitter()
The event emiter should stay here, otherwise it does not work

2024-01-17 16:06 UTC, bogdanfazakas commented on src/components/Indexer/index.ts
> -export const INDEXER_DDO_EVENT_EMITTER = new EventEmitter()
good catch, might be something related to working threads, let me dig more into this

2024-01-18 12:41 UTC, mariacarmina approved these changes
lgtm

2024-01-18 13:32 UTC, jamiehewitt15 reviewed
Looks good in general, but it would be good to have unit tests that instantiate the new classes and then call the public methods.

2024-01-18 17:25 UTC, paulo-ocean commented
its still not working @bogdanfazakas 
Are you posting the mesaage? This part is not getting called
```
worker.on('message', (event: any) => {
        if (event.method === EVENTS.METADATA_CREATED) {
          this.advertiseDDO(event.network, event.data, event.method)
        } 
})
```
Also you are already checking if `event.method === EVENTS.METADATA_CREATED)` for calling `advertiseDDO` but you're doing again the same check there, is that really necessary? Or the fact that it reruns a Promise?
public async advertiseDDO(network: number, ddo: any, method: string): Promise<void> {
```
    if (method === EVENTS.METADATA_CREATED) {
      INDEXER_LOGGER.logMessage(
        `Advertising new DDO : ${ddo.id} from network: ${network} `
      )
      INDEXER_DDO_EVENT_EMITTER.emit(EVENTS.METADATA_CREATED, ddo.id)
    }
  }
```
thanks

2024-01-18 19:30 UTC, paulo-ocean reviewed
still not working, please see my previous comment

2024-01-22 08:01 UTC, bogdanfazakas commented
> still not working, please see my previous comment



> its still not working @bogdanfazakas Are you posting the message? This part is not getting called:
> 
> ```
> worker.on('message', (event: any) => {
>         if (event.method === EVENTS.METADATA_CREATED) {
>           this.advertiseDDO(event.network, event.data, event.method)
>         } 
> })
> ```
> 
> Also you are already checking if `event.method === EVENTS.METADATA_CREATED)` for calling `advertiseDDO` but you're doing again the same check there, is that really necessary? Or the fact that it returns a Promise?
> 
> ```
> public async advertiseDDO(network: number, ddo: any, method: string): Promise<void> {
>     if (method === EVENTS.METADATA_CREATED) {
>       INDEXER_LOGGER.logMessage(
>         `Advertising new DDO : ${ddo.id} from network: ${network} `
>       )
>       INDEXER_DDO_EVENT_EMITTER.emit(EVENTS.METADATA_CREATED, ddo.id)
>     }
>   }
> ```
> 
> PS: you can try to use the ocean-cli to publish with the node running and double check it thanks

Sorry my mistake, there was a typo `processBlocks` instead of `processedBlocks` 😮‍💨

2024-01-22 10:48 UTC, jamiehewitt15 commented
> adding this unit tests is a bit complex since it requires a lot of mocked data, we need to mock all database interactions and the contract calls as well, i did the database mocks but the contact mocks require more work, the other way around with adding barge and having actual contract calls like we have in ocean.js for eg is somehow breaking the concepts of unit tests. let's have a talk at todays meetings and see if we need to spend more time on it or we should focus on something else,

Yeah, that's fair enough.

2024-01-22 15:14 UTC, paulo-ocean commented
alright, working now :+1:

2024-01-22 15:15 UTC, paulo-ocean approved these changes

2024-01-22 15:22 UTC, merged