decrypt ddo command
oceanprotocol/ocean-node pull request #212
Opened 2024-01-10 13:32 UTC by an7e

Fixes #53

Changes proposed in this PR:

- 
- 
-

2024-01-16 10:03 UTC, mariacarmina commented
Hello @an7e, is this draft PR still work in progress? I've seen that you have some conflicts on this branch. Thanks!

2024-01-17 09:47 UTC, bogdanfazakas commented
Hi Ilia, i think the following is missing from the task definition

- [ ]  expose it on http interface

2024-01-17 10:00 UTC, paulo-ocean commented
> Hi Ilia, i think the following is missing from the task definition
> 
> * [ ]   expose it on http interface

It is via directCommand, 
It looks good to me unless we are talking about the legacy API/URL ?

2024-01-17 10:03 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +export class DecryptDdoHandler extends Handler {
Please add the handler to `CoreHandlersRegistry` constructor
i noticed the NonceHandler(node) appears 2 time in that constructor (a bad merge of mine last week) so please fix that while you are at it.
thanks

2024-01-17 10:40 UTC, paulo-ocean commented
> > > Hi Ilia, i think the following is missing from the task definition
> > > 
> > > * [ ]     expose it on http interface
> > 
> > 
> > It is via directCommand, It looks good to me unless we are talking about the legacy API/URL ?
> 
> i was referring to the legacy API 😄 , though that was the meaning in the task definition

Well, honestly i don't know for sure, i would probably just do the directCommand as well, but you might be right, we do have "encrypt" on the provider routes so i guess the "decrypt" makes sense after all

2024-01-17 11:12 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +      if (existingNonce && existingNonce.nonce === nonce) {
hi @an7e
I'm not 100% sure of this logic implemented here.
What if the nonce on the request is lower than the one on DB?
You're just checking if is different, and if so, proceed, otherwise return error 

I'm not sure if this decrypt logic here is supposed to have something in common with the nonce handler functions or not, honestly.. .
But i remember than on the nonce, if the nonce did not existed on DB we created it with value 0 ... Then on the following requests, we would check if it was bigger than the existing one. Shouldn't we be using the core functions related with nonce here?? the ones on` core/utils/nonceHandler.ts` for instance?  Seems to me that we are just creating a new logic here without using the nonce logic that we already implemented..

2024-01-17 11:30 UTC, an7e commented on src/utils/config.ts
> +    !process.env.AUTHORIZED_DECRYPTERS ||
@paulo-ocean sure, added

2024-01-17 11:32 UTC, an7e commented on src/components/core/ddoHandler.ts
> +export class DecryptDdoHandler extends Handler {
@paulo-ocean I missed it while merging branches and solving conflits

2024-01-17 11:37 UTC, an7e commented on src/components/core/ddoHandler.ts
> +      if (existingNonce && existingNonce.nonce === nonce) {
I was relying on the provider's logic
https://github.com/oceanprotocol/provider/blob/4cd244bc18565c0d7bf631f97b584cbd199f0d03/ocean_provider/routes/decrypt.py
by logic, there should be no requests with the same nonce

2024-01-17 11:42 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +      if (existingNonce && existingNonce.nonce === nonce) {
> I was relying on the provider's logic https://github.com/oceanprotocol/provider/blob/4cd244bc18565c0d7bf631f97b584cbd199f0d03/ocean_provider/routes/decrypt.py by logic, there should be no requests with the same nonce

fair enough, you're right. Honestly i don't know how much of that provider code is buggy or not... looking at that code there is also the required "signature", that is never validated , strange

2024-01-17 16:33 UTC, paulo-ocean requested changes

2024-01-17 16:33 UTC, paulo-ocean commented on src/components/core/coreHandlersRegistry.ts
> -    this.registerCoreHandler(PROTOCOL_COMMANDS.DOWNLOAD, new DownloadHandler(node))
Where is the download handler now?

2024-01-17 17:16 UTC, an7e commented on src/components/core/coreHandlersRegistry.ts
> -    this.registerCoreHandler(PROTOCOL_COMMANDS.DOWNLOAD, new DownloadHandler(node))
@paulo-ocean it's very funny, but it's also sad that the tests didn't catch it

2024-01-18 09:41 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +            httpStatus: 400,
on the provider code this is a 403

2024-01-18 09:46 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +      if (
same thing here, on the provider, any of these 3 states return a 403 error code.
besides only  
```
MetadataState.ACTIVE,
MetadataState.TEMPORARILY_DISABLED,
MetadataState.UNLISTED,
```
seem valid, and the others (excluding the ones that trigger the 403)  should return 400.
This logic here does not match provider one

2024-01-18 10:15 UTC, an7e commented on src/components/core/ddoHandler.ts
> +            httpStatus: 400,
I wasn't sure if I should do that, but I fixed it

2024-01-18 10:15 UTC, an7e commented on src/components/core/ddoHandler.ts
> +      if (
I wasn't sure if I should do that, but I fixed it

2024-01-18 10:22 UTC, paulo-ocean commented on src/components/core/ddoHandler.ts
> +      if (
ok, but then i don't understand the task.. 
are we doing the same logic or just half of it? :-)

2024-01-18 11:00 UTC, paulo-ocean approved these changes
lgtm

2024-01-18 11:44 UTC, bogdanfazakas commented on src/components/httpRoutes/validateCommands.ts
> +        !requestBody.signature
i see signature beeing required but we never seem to use in the decrypt method, do we really need it ? i know we have it in old provider but not sure if used there as well, also the tests seem to just pass a random string value

2024-01-18 13:52 UTC, an7e commented on src/components/httpRoutes/provider.ts
> +providerRoutes.post('/decrypt', async (req, res) => {
@jamiehewitt15 `httpRoutes.use('/api/services/', providerRoutes)`

2024-01-18 13:56 UTC, jamiehewitt15 commented on src/components/httpRoutes/provider.ts
> +providerRoutes.post('/decrypt', async (req, res) => {
Ah yeah, sorry I missed that

2024-01-18 14:10 UTC, jamiehewitt15 commented on src/components/core/ddoHandler.ts
> +      // console.log('artifactsAdresses', artifactsAdresses)
```suggestion
```

2024-01-18 14:13 UTC, jamiehewitt15 commented on src/components/core/ddoHandler.ts
> +        status: { httpStatus: 500, error: 'Decrypt DDO: Unknown error: ' }
Why not return `error.message`?

2024-01-18 14:14 UTC, jamiehewitt15 commented on src/components/httpRoutes/provider.ts
> +    res.status(500).send('Internal Server Error')
Might also be useful to return `error.message` here as well: 

```suggestion
    res.status(500).send(`Internal Server error: ${error.message}`)
```

2024-01-18 14:59 UTC, an7e commented on src/components/core/ddoHandler.ts
> +        status: { httpStatus: 500, error: 'Decrypt DDO: Unknown error: ' }
I was afraid that if any sensitive information got into output

2024-01-18 15:01 UTC, an7e commented on src/components/httpRoutes/provider.ts
> +    res.status(500).send('Internal Server Error')
I was afraid that if any sensitive information got into output

2024-01-18 15:03 UTC, an7e commented on src/components/httpRoutes/validateCommands.ts
> +        !requestBody.signature
we're going to implement it

2024-01-19 13:04 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-01-19 14:13 UTC, merged