Create collections specific for ddo versions
oceanprotocol/ocean-node pull request #225
Opened 2024-01-19 12:13 UTC by mariacarmina

Fixes #207  .

Changes proposed in this PR:

- 
- 
-

2024-01-23 09:58 UTC, mariacarmina commented
Should I also modify `database/index.ts` for ddo database, where we basically retrieve the first schema, into choosing the schema by DDO version? Or this should be done in #205 ?
For the moment, we load the schemas mappings dinamically into typesense db. Let me know if it's needed in this PR to modify also the CRUD methods from `database/index.ts`. Thank you!

cc @alexcos20 @jamiehewitt15

2024-01-23 11:03 UTC, jamiehewitt15 commented
> Or this should be done in https://github.com/oceanprotocol/ocean-node/issues/205

I see what you mean there is some overlap between the two issues. I think it's fine to do it in the next PR, which keeps this one short and easy to review

2024-01-23 11:06 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-01-23 14:32 UTC, alexcos20 requested changes

2024-01-23 14:32 UTC, alexcos20 commented on src/components/database/schemas.ts
> +  const pathToSchemaDir: string = '../../../schemas/v4'
can we have just schema folder  (instead of schemas/v4 ? )

2024-01-23 15:05 UTC, mariacarmina commented on src/components/database/schemas.ts
> +  const pathToSchemaDir: string = '../../../schemas/v4'
done

2024-01-24 06:30 UTC, bogdanfazakas commented on src/components/database/schemas.ts
> +  const jsonDocuments: any[] = []
i think better to create a new type in src/@types with .json files fields and use that instead of any

2024-01-24 06:30 UTC, bogdanfazakas commented on src/components/database/schemas.ts
> +  const jsonFiles = fs
better to ensure also this one does not fail since not surounded with try catch block, at leas check if jsonFiles exists to avoind .forEach of undefined bellow

2024-01-25 09:54 UTC, paulo-ocean commented on src/components/database/index.ts
> +      this.ddo = await new DdoDatabase(this.config, schemas.ddoSchemas)
unnecessary change here, no need for the "this" keyword, not an issue but certainly unnecessary to change

2024-01-25 12:22 UTC, mariacarmina commented on src/components/database/index.ts
> +      this.ddo = await new DdoDatabase(this.config, schemas.ddoSchemas)
would you prefer to remove it?

2024-01-25 12:39 UTC, paulo-ocean commented on src/components/database/index.ts
> +      this.ddo = await new DdoDatabase(this.config, schemas.ddoSchemas)
any param marked as `private` in the constructor is automatically assigned (we don't need to create a matching property and assign on the class, typescript does that automatically)... its greyed out by the linter but we know better :-)
Anyway, i do not care at all, one way or the other is fine :+1:  .. just pointed it out because there was no need for that change

2024-01-25 12:56 UTC, paulo-ocean commented on src/components/database/schemas.ts
> +  if (!jsonFiles || jsonFiles === undefined) {
this is still not exactly fine @mariacarmina 
this piece:
```
const jsonFiles = fs
    .readdirSync(schemaFilePath)
    .filter((file) => path.extname(file) === '.json')
```
is not part of the try catch as @bogdanfazakas  mentioned. Besides that, the filter() will return an array [], which could be empty []

With an empty array, this part:

`if (!jsonFiles || jsonFiles === undefined) {`

Is Not executed

And it still will do the forEach() part without logging the error message :-(

2024-01-25 13:08 UTC, mariacarmina commented on src/components/database/index.ts
> +      this.ddo = await new DdoDatabase(this.config, schemas.ddoSchemas)
> its greyed out by the linter but we know better :-). It was being used
Yes, ofc it was used, otherwise it wasn't working properly. Thanks for pointing out, I have a habit to put `this` wherever needed within a class, good practice.

2024-01-25 13:10 UTC, mariacarmina commented on src/components/database/schemas.ts
> +  if (!jsonFiles || jsonFiles === undefined) {
Ok then I will include in the try/catch block as well. Thank you

2024-01-25 13:28 UTC, paulo-ocean reviewed
@mariacarmina please take a couple of minutes before rushing the commits :-)
If an exception is caught on the outer try/catch (have no idea why we need both but anyway)
The function returns **nothing**, it just logs a message, it should return empty array as well
tkx

2024-01-25 15:50 UTC, mariacarmina commented
> If an exception is caught on the outer try/catch (have no idea why we need both but anyway) The function returns **nothing**, it just logs a message, it should return empty array as well to be consistent tkx

I return now empty array in the outer try/catch block.

2024-01-25 18:52 UTC, paulo-ocean approved these changes
lgtm

2024-01-29 09:15 UTC, paulo-ocean approved these changes
lgtm

2024-01-29 11:23 UTC, bogdanfazakas approved these changes
lgtm

2024-01-29 12:07 UTC, mariacarmina commented
Thanks for approvals, but @alexcos20 needs to undo the requested changes status in order to merge it 😅

2024-01-30 12:56 UTC, alexcos20 approved these changes

2024-01-30 13:04 UTC, merged