Expose validateDDO on http
oceanprotocol/ocean-node pull request #234
Opened 2024-01-22 12:54 UTC by mariacarmina

Fixes #47  .

Changes proposed in this PR:

- added DDO validation endpoint for http interface

2024-01-23 10:54 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-01-23 16:27 UTC, paulo-ocean commented on src/components/httpRoutes/aquarius.ts
> +    if (!ddo.version) {
Duplicate line here

2024-01-23 16:39 UTC, paulo-ocean commented on src/components/httpRoutes/validateCommands.ts
> +    else if (command === PROTOCOL_COMMANDS.NONCE) {
We are not adding any params validation for the directCommand (only on aquarius route) ..
Are we going to do that on [https://github.com/oceanprotocol/ocean-node/issues/47](https://github.com/oceanprotocol/ocean-node/issues/47) ?
thanks

2024-01-25 10:46 UTC, mariacarmina commented on src/components/httpRoutes/validateCommands.ts
> +    else if (command === PROTOCOL_COMMANDS.NONCE) {
> We are not adding any params validation for the directCommand (only on aquarius route) ..
> Are we going to do that on https://github.com/oceanprotocol/ocean-node/issues/47 ?

From sprint planning discussion, @alexcos20 mentioned only the separate endpoint option in `aquarius.ts`. I have added before in `directCommand`. If I add the validation also here, that means that validateDDO command will be included within /directCommand route.

@alexcos20 can you confirm that `validateDDO` will be integrated in just a separate endpoint as it is in aquarius or can we have it also inside /directCommand route?

2024-01-25 10:57 UTC, mariacarmina commented on src/components/httpRoutes/validateCommands.ts
> +    else if (command === PROTOCOL_COMMANDS.NONCE) {
> Also, i noticed that we are not logging anything (errors) on ValidateDDOHandler (also happens on some other handlers) , if something fails we have no idea of what happened.. Only the client that initiated the request will get some info on the status response.

Regarding this, besides `extraErrors` which are for DDO object validation, the logs handle internal server error (where basically print the error found with status 500), failure in detecting and reading shacl schemas, unexisting validation report. If there are not enough, I think there is already an issue for adding logs or something similar if I am not wrong. But in the meantime, I have a retrieve from DB and a call to `validateObject` which can bring error. What other logs can be suitable for these 2 functions if they are already have a specific log for each of them?

2024-01-25 10:59 UTC, paulo-ocean commented on src/components/httpRoutes/validateCommands.ts
> +    else if (command === PROTOCOL_COMMANDS.NONCE) {
i don´t know, but this PR says it says it fixes #47 , and it includes http and p2p, that's why i'm asking..
from the description:
Command description:

```
{
command: "validateDDO",
node: "NodeB ID", // optional, if missing, it refers to current node
ddo: Object,
}
```
this is clearly the directCommand, but i know if we are addressing this issue into separate tasks or not

2024-01-25 11:01 UTC, mariacarmina commented on src/components/httpRoutes/validateCommands.ts
> +    else if (command === PROTOCOL_COMMANDS.NONCE) {
> this is clearly the directCommand, but i know if we are addressing this issue into separate tasks or not
I have added in [my first commit](https://github.com/oceanprotocol/ocean-node/pull/234/commits/bc47a8bad5f6cb89453760445d4d23e26f5bfa25#diff-9097c73b57fa2e60596f49b0309fdc0505e2cfb189f2d28f06782f716c353eefR39) from this PR :)
I can re-add here, no need to create a new issue.

2024-01-26 09:10 UTC, paulo-ocean requested changes

2024-01-26 09:10 UTC, paulo-ocean commented on src/components/httpRoutes/validateCommands.ts
> +    } else if (command === PROTOCOL_COMMANDS.VALIDATE_DDO) {
@mariacarmina , please check my previous comments. The `VALIDATE_DDO` has exactly the same required parameters of `FIND_DDO` and `GET_DDO` (the "id"), there is no need for another "if", its exactly the same code. You can aggregate the 3 in one. Also use `buildInvalidRequestMessage` lets not repeat again the same repetitive blocks that were removed before:
```
return {
          valid: false,
          reason: 'Missing or invalid required parameter: "id"',
          status: 400
        }
```
thanks

2024-01-29 09:03 UTC, paulo-ocean approved these changes
lgtm

2024-01-29 09:37 UTC, merged