Created function for retriving datatoken decimals.
oceanprotocol/ocean-node pull request #264
Opened 2024-02-14 08:32 UTC by mariacarmina

Fixes #262  .

Changes proposed in this PR:

- 
- 
-

2024-02-19 12:15 UTC, mariacarmina commented
For the moment, unit tests are facing an issue regarding TypeError on `insertLog` function and integration tests fail due to `stream not present` error because the file that is used inside tests is no longer available/reachable.

`response:  {
  stream: null,
  status: {
    httpStatus: 501,
    error: 'Unknown error: Request failed with status code 404'
  }
}`

`     AssertionError: expected 'Unknown' to equal '13873'
      + expected - actual
      -Unknown
      +13873`

Fixes for those problems are tackled in this PR #267

2024-02-21 11:07 UTC, jamiehewitt15 commented on src/test/integration/fees.test.ts
>          expect(feesData.v).to.be.gte(27) // 27 OR 28
This line here could be improved to check that the value is actually 27 or 28

```suggestion
        assert(feesData.v === 27 || (feesData.v === 27, 'Expected feesData.v to be 27 or 28')
```

2024-02-21 14:25 UTC, paulo-ocean requested changes

2024-02-21 14:25 UTC, paulo-ocean commented on src/components/core/utils/feesHandler.ts
> +  if (providerFeeToken && providerFeeToken !== ZeroAddress) {
This line is just wrong :-)

2024-02-21 14:40 UTC, paulo-ocean commented on src/components/core/utils/feesHandler.ts
> +  if (providerFeeToken && providerFeeToken !== ZeroAddress) {
`if (providerFeeToken !== ZeroAddress) {`  should be enough. 
Its always something OR ZeroAddress if not found

2024-02-21 14:47 UTC, paulo-ocean commented on src/utils/blockchain.ts
> +export async function getDatatokenDecimals(
Nothing wrong here, but just want to point out that overall,  we are, IMO, abusing a bit of asynchronous functions..
everything is `async function ` and everything is returning a `Promise`
We're kind of making this the standard for every single function we make, but it should not be the case every time
cheers

2024-02-26 09:15 UTC, mariacarmina commented on src/components/core/utils/feesHandler.ts
> +  if (providerFeeToken && providerFeeToken !== ZeroAddress) {
on `else` branch could be a good fit here

2024-02-26 09:20 UTC, mariacarmina commented on src/utils/blockchain.ts
> +export async function getDatatokenDecimals(
I agree, I've seen in multiple places, but here we have a contract call and needs `await`.

2024-02-26 09:28 UTC, mariacarmina commented on src/@types/commands.ts
> +  chainId?: number
Thanks, I'll look into this again

2024-02-26 11:15 UTC, jamiehewitt15 commented on src/utils/blockchain.ts
> +export async function getDatatokenDecimals(
We can use ESLint to find any functions that are using async but without an await call, which could help with this https://eslint.org/docs/latest/rules/require-await

2024-02-27 11:07 UTC, jamiehewitt15 commented on src/utils/blockchain.ts
> +export async function getDatatokenDecimals(
I've implemented the new ESLint rule on a separate PR, hopefully it helps avoid unnecessary usage of async: https://github.com/oceanprotocol/ocean-node/pull/284

2024-02-27 11:27 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-02-28 12:28 UTC, paulo-ocean commented on src/test/integration/fees.test.ts
>          expect(feesData.v).to.be.gte(27) // 27 OR 28
this line is still wrong:
```
assert(
          feesData.v === 27 || (feesData.v === 27, 'Expected feesData.v to be 27 or 28')
        )
```
it checks 2 times for 27

2024-02-29 11:26 UTC, paulo-ocean commented
@mariacarmina 
check the test about 'feesData.v' (on comments above)
Its not correct yet. It should be:
` assert( feesData.v === 27 || feesData.v === 28, 'Expected feesData.v to be 27 or 28')`
tkx

2024-03-11 11:19 UTC, mariacarmina commented
> @mariacarmina check the test about 'feesData.v' (on comments above) Its not correct yet. It should be: ` assert( feesData.v === 27 || feesData.v === 28, 'Expected feesData.v to be 27 or 28')` tkx

Fixed a lot of conflicts and now fees.test.ts file does not exist, can you point to the line of code that you are referring to in `Files Changed` tab? Thanks

2024-03-11 12:13 UTC, paulo-ocean commented
> > @mariacarmina check the test about 'feesData.v' (on comments above) Its not correct yet. It should be: ` assert( feesData.v === 27 || feesData.v === 28, 'Expected feesData.v to be 27 or 28')` tkx
> 
> Fixed a lot of conflicts and now fees.test.ts file does not exist, can you point to the line of code that you are referring to in `Files Changed` tab? Thanks

The file was deleted

2024-03-18 15:07 UTC, paulo-ocean approved these changes

2024-03-18 15:07 UTC, paulo-ocean commented on src/utils/blockchain.ts
> +    CORE_LOGGER.error(`${err}`)
we could return a default value, like 18 for instance, imo, it would be a good practice, but not a big deal cause parseUnits will do that for us anyway.

2024-03-18 15:41 UTC, mariacarmina commented on src/utils/blockchain.ts
> +  if (!(`${chainId.toString()}` in config.supportedNetworks)) {
Can you detail what you are referring to? It's a single if and I store config in a variable because I use further for retrieving network URL. Again, if you address this type of suggestions/assumptions regarding cosmetic changes, it's better to show them as well ;)

2024-03-18 16:20 UTC, paulo-ocean commented on src/utils/blockchain.ts
> +  if (!(`${chainId.toString()}` in config.supportedNetworks)) {
yes, it could be useful

2024-03-19 11:34 UTC, merged