40 command encryptfile
oceanprotocol/ocean-node pull request #268
Opened 2024-02-15 14:14 UTC by an7e

Fixes #40

2024-02-16 12:07 UTC, alexcos20 requested changes

2024-02-16 12:07 UTC, alexcos20 commented on src/@types/fileObject.ts
> +  headers?: HeadersObject
Why only one?
We can have several headers for the same storage object

2024-02-16 12:07 UTC, alexcos20 commented on src/components/core/encryptHandler.ts
> +      if (task.files.type === 'url') {
please, we have Storage clases, use that.
Two weeks from now when we are going to add S3 storage, we have to search for hardcoded things..
And then do it again, four weeks later, when adding Azure Blob :)

2024-02-16 12:31 UTC, an7e commented on src/@types/fileObject.ts
> +  headers?: HeadersObject
@alexcos20 What do you mean by "several"?
like this ?
`headers: [ { "header1": "qwe" }, { "header2": "asd" } ]`
because HeadersObject is a key-value object, and usually headers are passed like this
`headers: { "header1": "qwe", "header2": "asd" }`

2024-02-23 09:00 UTC, paulo-ocean commented on src/@types/fileObject.ts
> +  headers?: HeadersObject
it was done

2024-02-23 09:01 UTC, paulo-ocean commented on src/components/core/encryptHandler.ts
> +      if (task.files.type === 'url') {
it was done

2024-02-23 15:57 UTC, alexcos20 approved these changes
lgtm

2024-02-23 18:18 UTC, paulo-ocean approved these changes

2024-02-23 18:19 UTC, merged