Initialize compute
oceanprotocol/ocean-node pull request #270
Opened 2024-02-19 10:37 UTC by mariacarmina

Fixes #230  .

Changes proposed in this PR:

- 
- 
-

2024-02-21 10:16 UTC, jamiehewitt15 commented on src/components/core/compute.ts
> +      CORE_LOGGER.logMessage(`Service was not found: ${err}`)
It would be better to log an error rather than just a message: 

```suggestion
      CORE_LOGGER.error(`Service was not found: ${err}`)
```

2024-02-21 10:19 UTC, jamiehewitt15 commented on src/components/core/utils/feesHandler.ts
> +    CORE_LOGGER.logMessage(`Validation for compute provider fees failed due to: ${err}`)
It would make sense to log an error here rather than a message `CORE_LOGGER.error()`

2024-02-21 10:26 UTC, jamiehewitt15 commented on src/test/integration/computeFees.test.ts
> +  delay(1000)
Paulo has a seperate PR removing all the delays so I would avoid adding another one here

2024-02-21 10:26 UTC, jamiehewitt15 commented on src/test/integration/computeFees.test.ts
> +    // const encryptedDataString = encryptedData.toString('base64')
```suggestion
```

2024-02-26 08:18 UTC, alexcos20 requested changes

2024-02-26 08:18 UTC, alexcos20 commented on src/@types/commands.ts
> +export interface Dataset {
see https://github.com/oceanprotocol/ocean-node/pull/279/files#diff-c19a166d9cbd78d7cfe5a671f3a2d151ea75b829ed97b46f989bc9c4945f9235

2024-02-26 08:18 UTC, alexcos20 commented on src/components/core/compute.ts
> +      const listOfAssest = [...task.datasets, ...[task.algorithm]]
this should be a separate function, because startCompute will use this as well to validate the request

2024-02-26 17:24 UTC, mariacarmina commented on src/test/integration/computeFees.test.ts
> +  delay(1000)
no more delays after merging with develop

2024-02-26 17:27 UTC, mariacarmina reviewed
I also need to expose initializeCompute via http.

2024-02-27 11:51 UTC, alexcos20 commented on src/components/core/compute.ts
> +      const listOfAssest = [...task.datasets, ...[task.algorithm]]
yes, we need to check in startCompute if fees were paid

2024-02-27 15:43 UTC, mariacarmina commented on src/components/core/compute.ts
> +      const listOfAssest = [...task.datasets, ...[task.algorithm]]
I have created a separate function but for the moment if the order is expired or there is no transaction Id for an order, I calculate another provider fees.

2024-02-28 15:14 UTC, paulo-ocean commented on src/components/core/compute.ts
> +          const provider = new JsonRpcProvider(networkUrl)
if we use the existing `Blockchain` class we already have it
`constructor(rpc: string, chaindId: number) {`
...
```
public getProvider(): JsonRpcApiProvider {
    return this.provider
  }
```

2024-02-28 20:38 UTC, mariacarmina commented
Still need to test via ocean-cli, but if you have other suggestions regarding the code, it will be open for review.

2024-02-29 09:50 UTC, alexcos20 approved these changes

2024-02-29 09:50 UTC, alexcos20 approved these changes
lgtm

2024-02-29 09:52 UTC, bogdanfazakas approved these changes
besides some small remarks looks good

2024-02-29 09:52 UTC, bogdanfazakas commented on src/components/httpRoutes/compute.ts
> +      res.status(result.status.httpStatus).send(result.status.error)
maybe worth adding a log here as well with the result error

2024-02-29 10:10 UTC, mariacarmina commented on src/components/core/compute.ts
> +          const provider = new JsonRpcProvider(networkUrl)
I created an util function, not inside the class. Do we want to create a blockchain instance in order to create JsonRpcProvider? Is still valid suggestion? @paulo-ocean I can include if you want, no worries, but let me know if you are satisfied with the current changes

2024-02-29 16:55 UTC, merged