Remove logs
oceanprotocol/ocean-node pull request #301
Opened 2024-02-29 15:11 UTC by jamiehewitt15

Fixes # .

Changes proposed in this PR:

- 
- 
-

2024-03-05 08:37 UTC, alexcos20 requested changes

2024-03-05 08:37 UTC, alexcos20 commented on src/components/database/index.ts
> +    const xTime = parseInt(process.env.LOG_RETENTION_TIME || '2592000000') // Default to 30 days in milliseconds
instead of using process.env , can you pls use src/utils/constants.ts ?

2024-03-05 09:48 UTC, paulo-ocean reviewed
@jamiehewitt15 
I think maybe its worth to have a look at winston log rotation capabilities, there are projects like:
[https://www.npmjs.com/package/winston-daily-rotate-file](url)
and others.

maybe we can have this automatically integrated in winston transports in a more smoother way ( But i'm not sure how / if this applies to custom transports like DB or just files)

Also, don't forget to update ENVIRONMENT_VARIABLES on constants.ts

thanks

2024-03-08 13:11 UTC, bogdanfazakas commented on src/components/database/index.ts
> +        maxLogs = 250
would it be helpful to have a log message here to inform the users that the logs number was capped to 250 ?

2024-03-08 13:11 UTC, bogdanfazakas commented on src/components/database/index.ts
> +    const xTime = parseInt(ENVIRONMENT_VARIABLES.LOG_RETENTION_TIME.value || '2592000000') // Default to 30 days in milliseconds
maybe worth storing the default 2592000000 value in a const

2024-03-08 13:11 UTC, bogdanfazakas commented on src/index.ts
> +  cron.schedule('0 0 * * *', async () => {
think would be cleaner to have a helper that sets this cron and have just one call in the index.ts file

2024-03-11 10:51 UTC, alexcos20 requested changes

2024-03-11 10:51 UTC, alexcos20 commented on src/components/database/index.ts
> +      if (maxLogs > 250) {
can we move '250' to a env as well ?

2024-03-11 11:37 UTC, jamiehewitt15 commented on src/components/database/index.ts
> +      if (maxLogs > 250) {
We could but it's just going to lead to users getting an error. If they want more logs they will change the env above 250 and get the `Only up to 250 hits can be fetched per page.` error. If someone wants fewer logs they can already use the `maxLogs` parameter when they make a request.

If we need to request more than 250 logs then we should introduce pagination.

2024-03-11 12:04 UTC, jamiehewitt15 commented on src/components/database/index.ts
> +      if (maxLogs > 250) {
I have created a separate issue for introducing pagination as applies to all our collections, not just the logs database: https://github.com/oceanprotocol/ocean-node/issues/330

2024-03-11 14:22 UTC, bogdanfazakas approved these changes
lgtm

2024-03-21 12:54 UTC, jamiehewitt15 commented on src/components/database/index.ts
> +      if (maxLogs > 250) {
@alexcos20 can you have another look at this PR? As agreed in the meeting, we will introduce pagination rather than having an env here for `maxLogs`

2024-03-25 11:47 UTC, mariacarmina approved these changes
lgtm

2024-03-25 13:43 UTC, merged