Auth admin route
oceanprotocol/ocean-node pull request #319
Opened 2024-03-05 13:04 UTC by mariacarmina

Fixes #296 .

Changes proposed in this PR:

- add admin route for auth
- 
-

2024-03-06 07:39 UTC, jamiehewitt15 commented
Either in this PR or another one, we also need a simple endpoint that will return the array of admin addresses.

2024-03-06 07:42 UTC, jamiehewitt15 commented on src/test/integration/dashboard.test.ts
> +describe('Should run a complete node flow.', async () => {
```suggestion
describe('Should run the authentication flow.', async () => {
```

2024-03-06 07:45 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +    HTTP_LOGGER.logMessage(`Message for signature validation: ${message}`)
I don't think there is much value in logging this

2024-03-06 07:48 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +export function validateSignature(
This is a very generalized function that can also used by P2P commands if they need authentication. I think it would be better placed in the `src/utils` folder rather than `src/components/httpRoutes/dashboard/utils`

2024-03-06 07:48 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +  nonce: number,
```suggestion
```
no need for a nonce

2024-03-06 07:48 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +      toUtf8Bytes(nonce.toString() + '-' + expiryTimestamp.toString())
```suggestion
      toUtf8Bytes(expiryTimestamp.toString())
```

2024-03-06 10:27 UTC, paulo-ocean commented on .github/workflows/ci.yml
> +          ALLOWED_ADMINS: '[]'
If this is not required, it should not have a default value (a missing value could be interpreted as an empty array as well). Also we should have the same setting on `test/.env.test` (in this case, if no default, then should not be set anywhere)
tkx

2024-03-06 10:42 UTC, paulo-ocean requested changes

2024-03-06 10:42 UTC, paulo-ocean commented on src/components/httpRoutes/dashboard/admin.ts
> +export const aquariusRoutes = express.Router()
this is not another `aquariusRoutes` :-) this name is clashing with the real aquariousRoutes on `aquarius.ts`
besides, it should be imported on `httpRoutes/index.ts` otherwise its not used at all

2024-03-06 10:51 UTC, paulo-ocean commented on src/test/integration/dashboard.test.ts
> +    console.log(`envs: ${JSON.stringify(ENVIRONMENT_VARIABLES)}`)
better clean the console.log()
besides, do we really need to override all those ENV variables on setupEnvironment? I think only ALLOWED_ADMINS would be necessary here.
I also don't understand the purpose of this part:
```
//  eslint-disable-next-line no-unused-vars
    const indexer = new OceanIndexer(database, mockSupportedNetworks)

    let network = getOceanArtifactsAdressesByChainId(DEVELOPMENT_CHAIN_ID)
    if (!network) {
      network = getOceanArtifactsAdresses().development
    }
```
Why do we need the database, indexer, and the 'network' check?

Overall i think we should instead have a 'unit' test and not an 'integration' test, to check the signature validation with the allowed admins.. not the axios HTTP call for the endpoint
thanks

2024-03-06 11:01 UTC, paulo-ocean requested changes

2024-03-06 11:01 UTC, paulo-ocean commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +    if (!existsEnvironmentVariable('ALLOWED_ADMINS')) {
that's wrong usage of the function, should be:
`!existsEnvironmentVariable(ENVIRONMENT_VARIABLES.ALLOWED_ADMINS)`

2024-03-06 11:03 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/admin.ts
> +export const aquariusRoutes = express.Router()
Yeah true, although the easier option would just be to remove HTTP endpoint altogether. In standup yesterday we agreed the dashboard wouldn't use an HTTP endpoint for authentication. We just need a simple endpoint that returns the array of public addresses for admin users. The `validateSignature` function will be used by the other endpoints (yet to be added) that require validation. 

The updated flow is outlined [here](https://github.com/oceanprotocol/ocean-node/issues/288#issuecomment-1978948960)

2024-03-06 11:06 UTC, paulo-ocean commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +    for (const address of JSON.parse(process.env.ALLOWED_ADMINS)) {
Overall, i think its better to read this on getConfiguration() and make this part of the config, 
check if the variable exists: 
`existsEnvironmentVariable(ENVIRONMENT_VARIABLES.ALLOWED_ADMINS)`
if not or there are errors parsing it, set it as an empty array, 
if it exists, parse the array and make sure we have valid addresses and not something else..
expose it on config
tkx

2024-03-06 12:17 UTC, mariacarmina commented
> Either in this PR or another one, we also need a simple endpoint that will return the array of admin addresses.

I'll do it in this PR.

2024-03-06 12:26 UTC, mariacarmina commented on src/components/httpRoutes/dashboard/utils/utils.ts
> +    for (const address of JSON.parse(process.env.ALLOWED_ADMINS)) {
I'll use this information for admin list endpoint that @jamiehewitt15 reffered to. Thank you!

2024-03-06 12:39 UTC, mariacarmina commented on src/components/httpRoutes/dashboard/admin.ts
> +export const aquariusRoutes = express.Router()
Created only validateSignature and `adminList` endpoint.

2024-03-07 14:00 UTC, mariacarmina commented
Postman response for `directCommand` calling status handler:
<img width="883" alt="Screenshot 2024-03-07 at 15 59 50" src="https://github.com/oceanprotocol/ocean-node/assets/50501033/352534ee-4abc-4d62-902c-1675344b2600">

2024-03-07 14:27 UTC, jamiehewitt15 commented on src/components/httpRoutes/dashboard/admin.ts
> +adminRoutes.get(`/adminList`, async (req, res) => {
Seeing as we're now sending the array of admin addresses in the status response, we don't need this endpoint

2024-03-07 15:19 UTC, mariacarmina commented on src/components/httpRoutes/dashboard/admin.ts
> +adminRoutes.get(`/adminList`, async (req, res) => {
Missed that spot, deleted now. Thanks

2024-03-08 06:35 UTC, jamiehewitt15 commented on src/test/integration/download.test.ts
> +  // const publisherAddress = await publisherAccount.getAddress()
```suggestion
```

2024-03-08 08:11 UTC, bogdanfazakas commented on src/components/core/utils/statusHandler.ts
> +      if (regex.test(admin) === true) {
do we need to have our own regular expression and test the address against it? 
is there a reason we are not using `isAddress()` from ethers utils ?

2024-03-08 08:30 UTC, bogdanfazakas commented on src/@types/commands.ts
> +export interface GetAdminListCommand extends Command {}
do we still need this ?

2024-03-08 08:59 UTC, mariacarmina commented on src/components/core/utils/statusHandler.ts
> +      if (regex.test(admin) === true) {
I checked the docs for ethers and I have seen that it accepts whatever format as a string. No need to have that regex expr, I'll use `isAddress`. Thanks!

2024-03-08 09:00 UTC, mariacarmina commented on src/@types/commands.ts
> +export interface GetAdminListCommand extends Command {}
Nope, I'll delete it

2024-03-08 12:24 UTC, jamiehewitt15 approved these changes
I've tested locally and it's working well

2024-03-08 12:34 UTC, bogdanfazakas approved these changes
Lgtm

2024-03-08 13:32 UTC, mariacarmina commented on src/utils/auth.ts
> +    for (const address of JSON.parse(process.env.ALLOWED_ADMINS)) {
I should also add here status handler call instead of getting the envs.

2024-03-08 15:56 UTC, paulo-ocean commented on src/utils/config.ts
> +    allowedAdmins: getEnvValue(process.env.ALLOWED_ADMINS, [])
This is not OK @mariacarmina .
`getEnvValue()` is parsing Strings..
If you set a valid .env var like for instance:
`export ALLOWED_ADMINS=["0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"]`
The node crashes when getting the command Status (from status handler)
Because you're trying to parse an array but the value was initially read as a plain String
tkx

2024-03-08 16:02 UTC, paulo-ocean commented on src/components/core/utils/statusHandler.ts
> +    for (const admin of JSON.parse(config.allowedAdmins)) {
This line crashes the node, because the .env var was initially read as String, instead of Array of strings..
Besides, all the parsing & validation (including address check)  should be done on the config, when we first read the setting..
Not here... here its too late, and its doing the same checks every time it gets called, while it should already be fine on config, and here is just has to read it from there. Even if if it's an empty array, no problem.. You just need to add whatever is there to the response
tkx

2024-03-08 16:56 UTC, paulo-ocean commented on src/components/core/utils/statusHandler.ts
> +    for (const admin of JSON.parse(config.allowedAdmins)) {
Anyway, lets close this as is.
I created another issue: [https://github.com/oceanprotocol/ocean-node/issues/328](url)
and will address the refactor as well
tkx

2024-03-08 16:57 UTC, paulo-ocean approved these changes

2024-03-11 10:01 UTC, mariacarmina commented on src/utils/config.ts
> +    allowedAdmins: getEnvValue(process.env.ALLOWED_ADMINS, [])
Yes, I had some troubles with that, but in the end I convert within status handler and the list of addresses appears fine. How would you prefer? To parse in the config or to keep parsing logic inside status handler?

2024-03-11 10:59 UTC, mariacarmina commented on src/utils/config.ts
> +    allowedAdmins: getEnvValue(process.env.ALLOWED_ADMINS, [])
I have added for config.

2024-03-11 11:24 UTC, mariacarmina commented
Fixed the comments and tested again on postman, seems to work fine:

<img width="867" alt="Screenshot 2024-03-11 at 13 24 30" src="https://github.com/oceanprotocol/ocean-node/assets/50501033/058e1d1a-747f-4289-85e4-ce92fa4a2732">
I'll merge it, thanks for reviews

2024-03-11 11:25 UTC, merged