Collect fees handler
oceanprotocol/ocean-node pull request #491
Opened 2024-06-10 14:59 UTC by mariacarmina

Fixes #294  .

Changes proposed in this PR:

- 
- 
-

2024-06-12 08:51 UTC, paulo-ocean commented on src/components/core/utils/feesHandler.ts
> -    return localOceanToken || ethers.ZeroAddress
Hi @mariacarmina 
 `localOceanToken` can still be null or undefined here, so we should return `ZeroAddress` in that case, which is basically as it was before
tkx

2024-06-12 08:51 UTC, paulo-ocean commented on src/components/core/utils/feesHandler.ts
> +  if (chainId) {
Hi @mariacarmina 
I think we should at least check if the chainId is valid and supported (or we can do it before.. check the other comments)

Afaik, he original idea of this function was just to get the node **wallet address**, which is always the same for EVM chains, so the chain id would not be needed for that.

If we are "extending" the function usage, and want to perform operations with the wallet, we probably could be using the `utils/blockchain` class instead.. which already handles the provider, signer, etc..
So, we could probably refactor the function to create an instance of blockchain and get the wallet from there

thanks

2024-06-12 08:51 UTC, paulo-ocean commented on src/components/core/admin/collectFeesHandler.ts
> +    if (
Hi, 
We should be validating all mandatory parameters like the `chainId` as well like:
`if (!validateCommandParameters(command, ['chainId'])) {`

Imo, we don't need our own regex test for checking addresses, we can just use `isAddress()` function from ethers (we are using it in many other places as well)

Additionally, we should also check if the chainId is supported (not just provided as param) like:
`await checkSupportedChainId(task.chainId)` 
(check the reindex commands for instance)
thanks

2024-06-12 09:21 UTC, paulo-ocean commented on src/components/core/admin/collectFeesHandler.ts
> +        task.tokenAddress === ZeroAddress ||
Hi 
I think we might be missing something else here.
From the issue definition:
```
Input params:
token address (if 0x0 = native token for that chain)
```
So, if the token address is the ZeroAddress, we should use the native token of the chain, not reject it
as far as i understand it, if the providerFeeToken is not set (ZeroAddress) and we also send the ZeroAddress, we should work with the native token of the chain
thanks

2024-06-14 10:00 UTC, paulo-ocean approved these changes
LGTM, 
some minor tweaks could still be done

2024-06-14 10:03 UTC, mariacarmina commented on src/components/core/utils/feesHandler.ts
> +    const blockchain = new Blockchain(rpc, network, chainId, fallbackRPCs)
ok, I'll add this, sure. Thanks!

2024-06-17 16:07 UTC, alexcos20 commented on src/components/core/admin/collectFeesHandler.ts
> +        // for the moment I put Ocean token from address.json
if tokenAddress is 0x00, then you need to transfer native tokens (ETH, Matic, etc)

2024-06-18 08:48 UTC, alexcos20 requested changes
see my comments

2024-06-19 12:12 UTC, jamiehewitt15 commented on src/components/core/admin/collectFeesHandler.ts
> +      if (task.tokenAddress === ZeroAddress) {
Can you make sure that all the address comparisons are done in lowercase? 

```suggestion
      if (task.tokenAddress?.toLowerCase() === ZeroAddress) {
```

2024-06-21 09:39 UTC, bogdanfazakas commented on src/components/core/admin/collectFeesHandler.ts
> +        const msg: string = `Reverted transaction: ${receipt}`
isn't receipe here an object ? wouldn't it be better to add one the receipt properties to this message ?

2024-06-21 09:41 UTC, bogdanfazakas commented on src/components/core/utils/feesHandler.ts
> +    const blockchain = new Blockchain(rpc, network, chainId, fallbackRPCs)
yeah agreed, but do we really need this method or we should always use the signer and provider from the blockchain class ?

2024-06-21 10:45 UTC, paulo-ocean commented on src/components/core/utils/feesHandler.ts
> +    const blockchain = new Blockchain(rpc, network, chainId, fallbackRPCs)
> yeah agreed, but do we really need this method or we should always use the signer and provider from the blockchain class ?

i think we could use it as a "shortcut", for when we want the wallet, otherwise we will be repeating "new Blockchain()" part in a lot of places

2024-06-21 12:39 UTC, mariacarmina commented on src/components/core/admin/collectFeesHandler.ts
> +      if (task.tokenAddress === ZeroAddress) {
tokenAddress is a mandatory parameter and validated that it's not missing, I'll add `toLowerCase()`, thanks.

2024-06-21 12:56 UTC, mariacarmina commented on src/components/core/admin/collectFeesHandler.ts
> +        const msg: string = `Reverted transaction: ${receipt}`
put logs property and stringified

2024-06-26 09:47 UTC, jamiehewitt15 commented on src/@types/commands.ts
> +  tokenAmount: number
Is it possible to make `tokenAmount` optional and make the default value the maximum available amount?

2024-06-28 08:38 UTC, mariacarmina commented on src/@types/commands.ts
> +  tokenAmount: number
I transfer the whole balance if token amount is not provided.

2024-06-28 09:22 UTC, jamiehewitt15 commented on src/@types/commands.ts
> +  tokenAmount: number
Ok nice, thank you

2024-07-02 10:42 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-08-13 12:35 UTC, alexcos20 approved these changes

2024-08-13 16:52 UTC, merged