Add default output stage.
oceanprotocol/ocean-node pull request #537
Opened 2024-07-08 13:35 UTC by mariacarmina

Fixes #536 .

Changes proposed in this PR:

- Add default output stage.

2024-07-11 09:46 UTC, paulo-ocean commented on src/components/c2d/compute_engines.ts
> +    let getOuput = {}
Not a big deal, but this could be simpler,  (there are also typos btw :-) )
for example:
```
// output stage
    let getOuput = {}
    if (output) {
      getOuput = output
    } else if (config.hasHttp) {
      getOuput = {
        metadataUri: `http://${await publicIp()}:${config.httpPort}`
      }
    } 
```

2024-07-30 12:48 UTC, jamiehewitt15 commented on src/components/c2d/compute_engines.ts
> +        metadataUri: `http://${await publicIp()}:${config.httpPort}`
It would be a good idea to check that we have a valid response from `await publicIp()`. There could be some edge cases where it fails or returns undefined.

2024-07-30 13:04 UTC, mariacarmina commented on src/components/c2d/compute_engines.ts
> +        metadataUri: `http://${await publicIp()}:${config.httpPort}`
Sure good catch.

2024-08-02 08:32 UTC, paulo-ocean commented on src/components/c2d/compute_engines.ts
> +import { publicIp } from 'public-ip'
we have some IP utils functions for this under `src/utils/ip.ts`, we can use those. I think there's no need to install a package for such a simple function. Its the same kind of logic so it doesn't add.
We can probably improve to always have a default (even if it is just 'localhost') if something fails
tkx

2024-08-14 11:36 UTC, alexcos20 requested changes
This is not how the overall architecture works!

metadataUri is used by pod-configuration to know where to fetch DDOs from (https://github.com/oceanprotocol/pod-configuration/blob/4ba2172b7ca2e1804f74b13d9a6126983b67a363/src/index.js#L95)

Making that public IP covers only one small edge case

Example
 - you have a network with private IPS.  192.168.0.2 is used by node , and your kubernetes cluster is using class 10.0.0.1/24 for pods.   And you have no port forwarding.      Setting metadataUri to some external IP will not make pod-configuration working by magic..
 
 Remove this PR please and replace it with:
  - add an env variable, called C2D_NODE_URI .   And use that. It's up to the network administrator to set this properly

2024-08-14 15:48 UTC, mariacarmina commented
> This is not how the overall architecture works!
> 
> metadataUri is used by pod-configuration to know where to fetch DDOs from (https://github.com/oceanprotocol/pod-configuration/blob/4ba2172b7ca2e1804f74b13d9a6126983b67a363/src/index.js#L95)
> 
> Making that public IP covers only one small edge case
> 
> Example
> 
> * you have a network with private IPS.  192.168.0.2 is used by node , and your kubernetes cluster is using class 10.0.0.1/24 for pods.   And you have no port forwarding.      Setting metadataUri to some external IP will not make pod-configuration working by magic..
> 
> Remove this PR please and replace it with:
> 
> * add an env variable, called C2D_NODE_URI .   And use that. It's up to the network administrator to set this properly

Ok sure then I'll let up to the user to set correctly, not trying to fallback to anything.

2024-08-14 15:48 UTC, closed without merging

2024-08-14 15:49 UTC, mariacarmina commented
closing this and will refactor the logic in another PR