Check if ddo state is active before executing node's commands.
oceanprotocol/ocean-node pull request #542
Opened 2024-07-08 15:07 UTC by mariacarmina

Fixes #540 .

Changes proposed in this PR:

- Check ddo state before executing core actions

2024-07-10 13:02 UTC, jamiehewitt15 requested changes
This PR doesn't follow the state specification. You are treating every non-zero state the same when they are actually meant to be different. For example: ordering the asset is allowed for state 5. 

You need to refer to the state specification in the docs: https://docs.oceanprotocol.com/developers/ddo-specification#state

2024-07-23 14:50 UTC, paulo-ocean requested changes

2024-07-23 14:50 UTC, paulo-ocean commented on src/components/core/compute/initialize.ts
> +          if (ddo && ddo.nft.state && isOrderingAllowedForAsset(ddo)) {
Hi Maria
It seems you have the logic inverted on all the IF blocks :-)
we have:
```
if (ddo && ddo.nft.state && isOrderingAllowedForAsset(ddo)) {
...
// return some error
} 
```
We actually want to return an error IF  =>  ` ! isOrderingAllowedForAsset(ddo) ` (if this fn returns false)

One other thing, is that we're also not considering that `ddo.nft` might be `undefined` , so every time we have like  `ddo.nft.state`  it can potentially break..

IMO, it would be a lot more easier if all the IFs were simply re-written  like:
```
if (! isOrderingAllowedForAsset(ddo)) {
...
// return some error
}
```

Then we can check all the necessary conditions inside` isOrdedingAllowedForAsset() `function, without repeating same lines everywhere... like for example:
```
export function isOrderingAllowedForAsset(asset: DDO): boolean {
  if (!asset) {
    return false
  } else if (
    asset.nft &&
    !(asset.nft.state in [MetadataStates.ACTIVE, MetadataStates.UNLISTED])
  ) {
    return false
  }

  return true
}
```
thanks

2024-07-24 11:32 UTC, jamiehewitt15 commented on src/components/httpRoutes/aquarius.ts
> +    }
This still doesn't seem right. For assets with state `1` and `4` they should be discoverable, which requires them to have a valid DDO. So why is the `/validate` endpoint blocked for these assets?

2024-07-24 11:45 UTC, mariacarmina commented on src/components/core/compute/initialize.ts
> +          if (ddo && ddo.nft.state && isOrderingAllowedForAsset(ddo)) {
sure, I'll modify accordingly.

2024-07-24 11:45 UTC, mariacarmina commented on src/components/httpRoutes/aquarius.ts
> +    }
Yes, that's right, for validate shouldn't be applicable.

2024-07-24 12:09 UTC, mariacarmina commented on src/components/core/compute/initialize.ts
> +          if (ddo && ddo.nft.state && isOrderingAllowedForAsset(ddo)) {
I'll also add to the isOrderingAllowedForAsset, the reason for possible errors in order to be logged.

```javascript

export function isOrderingAllowedForAsset(asset: DDO): OrdableAssetResponse {
  if (!asset) {
    return { 
       isOrdable: false,
       reason: `Asset provided is either null, either undefined ${asset}`
    }
  } else if (
    asset.nft &&
    !(asset.nft.state in [MetadataStates.ACTIVE, MetadataStates.UNLISTED])
  ) {
    return { 
       isOrdable: false,
       reason: "Nft not present in the asset or the state is different than ACTIVE or UNLISTED."
    }
  }

  return {
    isOrdable: true,
    reason: ''
  }
}
```

2024-07-26 08:24 UTC, paulo-ocean approved these changes
lgtm

2024-07-29 10:57 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-07-29 11:02 UTC, merged