Enable indexing networks
oceanprotocol/ocean-node pull request #596
Opened 2024-08-07 10:21 UTC by bogdanfazakas

Fixes #503  .

Changes proposed in this PR:

- 
- 
-

2024-08-12 12:53 UTC, jamiehewitt15 approved these changes
Looks good to me

2024-08-13 12:37 UTC, alexcos20 requested changes
Can you add pls INDEXER_NETWORKS description in readme?
Otherwise, lgtm

2024-08-13 12:39 UTC, mariacarmina approved these changes
lgtm

2024-08-14 11:46 UTC, alexcos20 approved these changes

2024-08-14 12:38 UTC, merged