Issue 768 env cpu mem
oceanprotocol/ocean-node pull request #799
Opened 2024-12-17 10:16 UTC by paulo-ocean

Fixes #768 

Changes proposed in this PR:

- set cpu options
- 
-

2024-12-24 06:37 UTC, alexcos20 requested changes

2024-12-24 06:37 UTC, alexcos20 commented on src/components/c2d/compute_engine_docker.ts
> +  const existingCPUs = os.cpus().length
why not take the docker system information from https://docs.docker.com/reference/api/engine/version/v1.47/#tag/System/operation/SystemInfo ?

2024-12-24 06:37 UTC, alexcos20 commented on src/components/c2d/compute_engine_docker.ts
> +  private async checkResources(job: DBComputeJob, container: Dockerode.Container) {
we can remove this

2025-01-06 14:27 UTC, paulo-ocean commented on src/components/c2d/compute_engine_docker.ts
> +  const existingCPUs = os.cpus().length
we were already using 'os' on other parts (like status), ans its pretty much the same.
anyway, i've  added the docker system info call + the 'os' one as well, as fallback

2025-01-08 09:20 UTC, alexcos20 approved these changes
lgtm

2025-01-08 10:51 UTC, merged